import pyglet

__author__ = 'aikikode'

IMAGES_RESOURCE = "data/images"
# SOUNDS_RESOURCE = "data/sounds"
# CONFIG_FILE = "settings.cfg"

pyglet.resource.path = [IMAGES_RESOURCE]
pyglet.resource.reindex()

MAX_ENEMIES = 8
ENEMY_ARMOR = 3000
DEFAULT_SPAWN_INTERVAL = 8
SPAWN_INTERVAL_COEF = 0.9
KILL_LIMIT_SPAWN_INTERVAL_CHANGE = 5
MIN_SPAWN_INTERVAL = 3

HEALTH_BONUS_TYPE = 1
KILLALL_BONUS_TYPE = 2

PLAYER_ARMOR = 10000

FPS = 60
GAME_SPEED = 1